import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./assets/nav/navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tyra Anglin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.gif" type="image/gif" />
      </Head>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col pl-52 pr-52 pt-20 pb-20 font-Lora">
          <Navbar />
          {children}
        </div>
        <div className="fixed bottom-[10px] right-[10px] text-[8px]">
          Sparkle SVG created by Daisy from the Noun Project
        </div>
      </body>
    </html>
  );
}
